package com.dev.langbotchain.langchain4j.spring.MessageAnalyzer.KeyWords;

import java.util.List;
public class MedicalCode {
    public static final List<String> MEDICAL_SENTENCES = List.of(
            "What are the symptoms of COVID-19?",
            "How do vaccines work?",
            "Can you explain the process of blood clotting?",
            "What are the risk factors for heart disease?",
            "What is the difference between type 1 and type 2 diabetes?",
            "How does chemotherapy work to treat cancer?",
            "What are the stages of pregnancy?",
            "What is the role of neurotransmitters in mental health?",
            "How does the immune system respond to infection?",
            "What are the causes of allergic reactions?",
            "What are the symptoms of Alzheimer's disease?",
            "How is hypertension diagnosed and treated?",
            "What is the function of the thyroid gland?",
            "How do antibiotics work to fight bacterial infections?",
            "What are the different types of anesthesia?",
            "What is the process of tissue regeneration?",
            "How does the respiratory system function?",
            "What are the risk factors for stroke?",
            "How is HIV/AIDS transmitted and treated?",
            "What are the stages of wound healing?",
            "What are the effects of sleep deprivation on the body?",
            "What is the role of vitamins and minerals in nutrition?",
            "How does the digestive system process food?",
            "What are the causes and treatments for depression?",
            "What are the symptoms of autoimmune diseases?",
            "How is cancer diagnosed and staged?",
            "What is the role of hormones in the body?",
            "How does the cardiovascular system function?",
            "What are the risk factors for osteoporosis?",
            "What is the difference between a virus and a bacteria?",
            "Create a Medical Report",
            "What are the symptoms of COVID-19?",
            "How do vaccines work?",
            "Can you explain the process of blood clotting?",
            "What are the risk factors for heart disease?",
            "What is the difference between type 1 and type 2 diabetes?",
            "How does chemotherapy work to treat cancer?",
            "What are the stages of pregnancy?",
            "What is the role of neurotransmitters in mental health?",
            "How does the immune system respond to infection?",
            "What are the causes of allergic reactions?",
            "What are the symptoms of Alzheimer's disease?",
            "How is hypertension diagnosed and treated?",
            "What is the function of the thyroid gland?",
            "How do antibiotics work to fight bacterial infections?",
            "What are the different types of anesthesia?",
            "What is the process of tissue regeneration?",
            "How does the respiratory system function?",
            "What are the risk factors for stroke?",
            "How is HIV/AIDS transmitted and treated?",
            "What are the stages of wound healing?",
            "What are the effects of sleep deprivation on the body?",
            "What is the role of vitamins and minerals in nutrition?",
            "How does the digestive system process food?",
            "What are the causes and treatments for depression?",
            "What are the symptoms of autoimmune diseases?",
            "How is cancer diagnosed and staged?",
            "What is the role of hormones in the body?",
            "How does the cardiovascular system function?",
            "What are the risk factors for osteoporosis?",
            "What is the difference between a virus and a bacteria?",
            "Create a Medical Report",
            "What are the common symptoms of a cold?",
            "How is the flu virus transmitted?",
            "What are the risk factors for asthma?",
            "What is the difference between acute and chronic pain?",
            "How is tuberculosis diagnosed and treated?",
            "What are the stages of wound healing?",
            "What is the role of the kidneys in the body?",
            "How does the liver detoxify substances?",
            "What are the causes and treatments for anxiety disorders?",
            "How does the endocrine system regulate metabolism?",
            "What are the effects of high cholesterol on heart health?",
            "What is the difference between a benign and malignant tumor?",
            "How is diabetes managed through diet and exercise?",
            "What are the symptoms of gastrointestinal diseases?",
            "How does the nervous system control muscle movement?",
            "What are the risk factors for developing cancer?",
            "What is the role of stem cells in regenerative medicine?",
            "How does the lymphatic system protect against infections?",
            "What are the effects of diabetes on the eyes and kidneys?",
            "What is the function of the spleen in the immune system?",
            "How do antiviral medications work to treat infections?",
            "What are the long-term effects of untreated mental health disorders?",
            "Create a Medical Report"
    );


    public static final List<String> MEDICAL_KEYWORDS = List.of(
            "abdomen",
            "absorption",
            "acupuncture",
            "acute",
            "addiction",
            "adrenal",
            "allergy",
            "anesthesia",
            "aneurysm",
            "anorexia",
            "antibiotic",
            "anxiety",
            "appendicitis",
            "arthritis",
            "asthma",
            "atherosclerosis",
            "autism",
            "autoimmune",
            "back",
            "benign",
            "biopsy",
            "birth",
            "bladder",
            "blood",
            "bone",
            "bowel",
            "brain",
            "breast",
            "bronchitis",
            "burn",
            "cancer",
            "cardiac",
            "cardiovascular",
            "cataract",
            "celiac",
            "cerebral",
            "chemotherapy",
            "chest",
            "childbirth",
            "cholesterol",
            "chronic",
            "circulatory",
            "colon",
            "congenital",
            "constipation",
            "coronary",
            "cough",
            "depression",
            "diabetes",
            "diagnosis",
            "diarrhea",
            "digestive",
            "disorder",
            "diverticulitis",
            "dizziness",
            "dysfunction",
            "ear",
            "eating",
            "edema",
            "electrocardiogram",
            "embolism",
            "emergency",
            "endocrine",
            "epidemic",
            "epilepsy",
            "esophagus",
            "examination",
            "exercise",
            "eye",
            "fever",
            "fibrosis",
            "flu",
            "fracture",
            "gallbladder",
            "gastrointestinal",
            "gene",
            "genetic",
            "glaucoma",
            "gout",
            "growth",
            "hair",
            "headache",
            "heart",
            "hepatitis",
            "hernia",
            "hormone",
            "hospital",
            "hypertension",
            "hypotension",
            "immune",
            "implant",
            "infection",
            "inflammation",
            "influenza",
            "injury",
            "insomnia",
            "intestine",
            "joint",
            "kidney",
            "laboratory",
            "laryngitis",
            "laser",
            "liver",
            "lumbar",
            "lung",
            "lymph",
            "malaria",
            "mammogram",
            "malnutrition",
            "mammography",
            "mass",
            "melanoma",
            "menopause",
            "mental",
            "metabolism",
            "migraine",
            "miscarriage",
            "molar",
            "muscle",
            "narcotic",
            "nervous",
            "neurological",
            "neuron",
            "neuropathy",
            "nipple",
            "nodule",
            "nutrition",
            "obesity",
            "obstetrics",
            "orthopedic",
            "ovarian",
            "overdose",
            "pain",
            "palliative",
            "pancreas",
            "pandemic",
            "paralysis",
            "parasite",
            "pathogen",
            "pelvis",
            "pneumonia",
            "poison",
            "pregnancy",
            "prostate",
            "psoriasis",
            "psychiatric",
            "puberty",
            "pulmonary",
            "puncture",
            "radiation",
            "radiology",
            "rehabilitation",
            "respiration",
            "respiratory",
            "rheumatism",
            "rheumatoid",
            "scoliosis",
            "seizure",
            "senior",
            "sensitivity",
            "shock",
            "sickle",
            "skin",
            "sleep",
            "sore",
            "spasm",
            "spine",
            "stroke",
            "substance",
            "surgery",
            "syndrome",
            "tendon",
            "testicle",
            "thyroid",
            "tissue",
            "tooth",
            "tuberculosis",
            "tumor",
            "ulcer",
            "ultrasound",
            "urethra",
            "urinalysis",
            "urinary",
            "uterus",
            "vaccination",
            "vaccine",
            "vascular",
            "vein",
            "virus",
            "vital",
            "vomiting",
            "wound"
    );

}
